@file:Suppress("SpellCheckingInspection")

import org.gradle.api.JavaVersion

internal object Versions {
    const val ASSERTJ = "3.13.2"
    const val AWSSDK = "2.10.19"
    const val AWS_JAVA_SDK = "1.11.414"
    const val AWS_LAMBDA_CORE = "1.2.0"
    const val AWS_LAMBDA_EVENTS = "2.2.2"
    const val AWS_LAMBDA_LOG4J2 = "1.1.0"
    const val BEN_MANES = "0.27.0"
    const val BINTRAY = "1.8.4"
    const val COMMONS_CSV = "1.7"
    const val COMMONS_NET = "3.6"
    const val DAGGER = "2.19"
    const val DETEKT = "1.0.0-RC12"
    const val DOKKA = "0.9.18"
    const val GUICE = "4.2.2"
    const val GRADLE = "6.0"
    const val GRAPHIQL_SPRING_BOOT_STARTER = "5.0.2"
    const val GRAPHQL_JAVA = "13.0"
    const val GRAPHQL_JAVA_TOOLS = "5.2.4"
    const val GRAPHQL_JAVA_SPRING_BOOT_STARTER_WEBFLUX = "1.0"
    const val GRAPHQL_SPRING_BOOT_STARTER = "5.0.2"
    const val HTTPCORE = "4.4.10"
    const val JACKSON = "2.9.9"
    val JAVA = JavaVersion.VERSION_11
    const val JAVAFX = "11.0.1"
    const val JAVAX_INJECT = "1"
    const val JMOCKIT = "1.43"
    const val JUNIT = "4.12"
    const val JUNIT5 = "5.5.2"
    const val KODEIN_DI_GENEREIC_JVM = "6.0.1"
    const val KOIN = "1.0.2"
    const val KOTLIN = "1.3.60"
    const val KOTLINX = "1.3.1"
    const val LOG4J = "2.11.2"
    const val LOG4J_KOTLIN = "1.0.0"
    const val LOMBOK = "1.18.4"
    const val MOCKITO = "3.0.0"
    const val MOCKK = "1.9.3"
    const val MOCK_FTP_SERVER = "2.7.1"
    const val NEBULA_PUBLISH = "9.4.5"
    const val NEBULA_RELEASE = "9.2.0"
    const val ORG_ECLIPSE_JDT_ANNOTATION = "2.2.100"
    const val PICOCLI = "4.0.4"
    const val RXJAVA = "2.2.4"
    const val SHADOW_JAR = "5.2.0"
    const val SHIPKIT = "2.2.5"
    const val SLF4J_API = "1.7.25"
    const val SPRING = "5.1.9.RELEASE"
    const val SPRING_BOOT = "2.1.8.RELEASE"
    const val SPRING_DEPENDENCY_MANAGEMENT = "1.0.6.RELEASE"
    const val STRIPE_JAVA = "7.0.0"
    const val TRUTH = "0.42"
    const val VALIDATION_API = "2.0.1.Final"
}
