package org.openjfx

object JavaFX {
    const val GROUP = "org.openjfx"
    const val VERSION = "11.0.1"
    // libraries below
    const val BASE = "javafx-base"
    const val CONTROLS = "javafx-controls"
    const val FXML = "javafx-fxml"
    const val GRAPHICS = "javafx-graphics"
    const val MEDIA = "javafx-media"
    const val SWING = "javafx-swing"
    const val WEB = "javafx-web"
}

const val `javafx-base` = "${JavaFX.GROUP}:${JavaFX.BASE}:${JavaFX.VERSION}"
const val `javafx-base-linux` = "${`javafx-base`}:linux"
const val `javafx-base-mac` = "${`javafx-base`}:mac"
const val `javafx-base-win` = "${`javafx-base`}:win"
const val `javafx-controls` = "${JavaFX.GROUP}:${JavaFX.CONTROLS}:${JavaFX.VERSION}"
const val `javafx-controls-linux` = "${`javafx-controls`}:linux"
const val `javafx-controls-mac` = "${`javafx-controls`}:mac"
const val `javafx-controls-win` = "${`javafx-controls`}:win"
const val `javafx-fxml` = "${JavaFX.GROUP}:${JavaFX.FXML}:${JavaFX.VERSION}"
const val `javafx-fxml-linux` = "${`javafx-fxml`}:linux"
const val `javafx-fxml-mac` = "${`javafx-fxml`}:mac"
const val `javafx-fxml-win` = "${`javafx-fxml`}:win"
const val `javafx-graphics` = "${JavaFX.GROUP}:${JavaFX.GRAPHICS}:${JavaFX.VERSION}"
const val `javafx-graphics-linux` = "${`javafx-graphics`}:linux"
const val `javafx-graphics-mac` = "${`javafx-graphics`}:mac"
const val `javafx-graphics-win` = "${`javafx-graphics`}:win"
const val `javafx-media` = "${JavaFX.GROUP}:${JavaFX.MEDIA}:${JavaFX.VERSION}"
const val `javafx-media-linux` = "${`javafx-media`}:linux"
const val `javafx-media-mac` = "${`javafx-media`}:mac"
const val `javafx-media-win` = "${`javafx-media`}:win"
const val `javafx-swing` = "${JavaFX.GROUP}:${JavaFX.SWING}:${JavaFX.VERSION}"
const val `javafx-swing-linux` = "${`javafx-swing`}:linux"
const val `javafx-swing-mac` = "${`javafx-swing`}:mac"
const val `javafx-swing-win` = "${`javafx-swing`}:win"
const val `javafx-web` = "${JavaFX.GROUP}:${JavaFX.WEB}:${JavaFX.VERSION}"
const val `javafx-web-linux` = "${`javafx-web`}:linux"
const val `javafx-web-mac` = "${`javafx-web`}:mac"
const val `javafx-web-win` = "${`javafx-web`}:win"
